backend:
  name: github
  repo: littlejohn-produce/cms
media_folder: '/images'
public_folder: '/images'
collections:
  - name: page
    label: Page
    folder: pages
    create: true
    slug: '{{slug}}'
    fields:
      - name: layout
        label: Layout
        widget: hidden
        default: generic
      - name: title
        label: Title
        widget: string
      - name: banner
        label: Banner
        widget: image
      - name: body
        label: Body
        widget: markdown
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - name: layout
        label: Layout
        widget: hidden
        default: generic
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publish Date
        widget: datetime
      - name: banner
        label: Banner
        widget: image
      - name: body
        label: Body
        widget: markdown
