backend:
  name: gitlab
  repo: littlejohn-produce/cms
  auth_type: implicit
  app_id: 283656bc0628a0f24a901f99638b669522d9fd3725c2615cf9ea1269722deef6
media_folder: '/images'
public_folder: '/images'
collections:
  - name: page
    label: Page
    folder: pages
    create: true
    slug: '{{slug}}'
    extension: json
    format: json
    fields:
      - name: layout
        label: Layout
        widget: hidden
        default: generic
      - name: title
        label: Title
        widget: string
      - name: videoUrl
        label: Video URL
        widget: string
        required: false
      - name: body
        label: Body
        widget: markdown
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: json
    format: json
    fields:
      - name: layout
        label: Layout
        widget: hidden
        default: generic
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publish Date
        widget: datetime
      - name: banner
        label: Banner
        widget: image
      - name: videoUrl
        label: Video URL
        widget: string
        required: false
      - name: body
        label: Body
        widget: markdown
  - name: pickupLocation
    label: Pickup Location
    folder: pickupLocations
    create: true
    slug: '{{slug}}'
    extension: json
    format: json
    fields:
      - name: id
        label: ID
        widget: string
      - name: title
        label: Title
        widget: string
      - name: address
        label: Address
        widget: string
